name: DynamicMarket
main: com.gmail.haloinverse.DynamicMarket.DynamicMarket
version: 0.4.6.1
author: HaloInverse
description: >
             A shop plugin building towards an interesting and flexible market system.
commands:
    shop:
       description: Accesses the shop command system.
       usage: |
              /<command>
              /<command> help <topic/command>
              /<command> <itemid>
              /<command> <subcommand> <args>